apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-01-01T13:40:19Z"
  labels:
    run: my-db
  name: my-db
  namespace: default
  resourceVersion: "4512"
  uid: bd834e56-7b3a-47bb-87a5-d725de85a355
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: abc123
    - name: MYSQL_USER
      value: user1
    - name: MYSQL_PASSWORD
      value: user1@mydb
    image: mysql:latest
    imagePullPolicy: Always
    name: my-db
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kf2vq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cluster-66dbf2c46722fdb9097e9dbe-d4p-worker-2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-kf2vq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-01-01T13:40:38Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-01-01T13:40:19Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-01-01T13:40:38Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-01-01T13:40:38Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-01-01T13:40:19Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e874f4f92853ffebc029d449642090d159f8276708c2e00372a0f1b902654ae6
    image: docker.io/library/mysql:latest
    imageID: docker.io/library/mysql@sha256:0255b469f0135a0236d672d60e3154ae2f4538b146744966d96440318cc822c6
    lastState: {}
    name: my-db
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-01-01T13:40:38Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kf2vq
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.62.11.229
  hostIPs:
  - ip: 10.62.11.229
  phase: Running
  podIP: 10.42.3.3
  podIPs:
  - ip: 10.42.3.3
  qosClass: BestEffort
  startTime: "2025-01-01T13:40:19Z"
